### ISSUE TITLE
Error: message: Invalid parameter for [shared-secrets]. Invalid value

### ISSUE THREAD

**Issue by CFRR** [CheckPointSW/ExportImportPolicyPackage#27]
Hello,

I'm trying to import and I'm getting this error:

Failed to import vpn-community-star with name [****]. Error: message: Invalid parameter for [shared-secrets]. Invalid value
code: generic_err_invalid_parameter

Thanks,

**Comment by chkp-royl** [comment]
Hi @CFRR,
Thank you for reporting this issue. In order to investigate it, I would like to get from you the following things:
1. Export file (.tar.gz) you try to import
2. Tool logs after execution
3. From which Mgmt version you did the export + to which Mgmt version you try to import ?

Please send me all the relevant data to royl@checkpoint.com and I will update once we fix it.

Thanks,
Roy
