### ISSUE TITLE
importing objects with tags

### ISSUE THREAD

**Issue by amoruck** [CheckPointSW/ExportImportPolicyPackage#37]
When importing objects with tags, tags payload is converted to list instead of dict and causes error during import:

```
Adding services-udp
Unknown tag name for object [port-udp-8089]
```

relevant service definition in json file (fields except tags, name, port omitted for readability)
```
    {
        .....
        "port": "8089",
        "tags.0.type": "tag",
        "tags.0.name": "JuniperJunosOS",
        "tags.0.comments": "",
        "name": "port-udp-8089",
    }
```
The error is printed after this conditional statement:
```
           if tag_name is None or tag_name == "":
                debug_log("Unknown tag name for object [{0}] - {1}".format(payload["name"],payload), True, True)
```
I have verified what payload looks like for object in question and it is list of strings, instead of dict:

```
'tags': [u'black', u'JuniperJunosOS', u'tag']
```
For other similiar structures (data with dots, like "aging") I see they are correctly converted to dict: 
```
'aggressive-aging': {'use-default-timeout': u'true', 'enable': u'true', 'timeout': u'15', 'default-timeout': u'0'}
```

**Comment by chkp-royl** [comment]
Hi @amoruck,
Thank you for reporting this issue.
That behavior looks very strange for me because tool firstly create tag by dict data and then convert 'tags' into list of strings as needed. In order to investigate it please do the following:
1. Reproduce the issue
2. Connect to MGMT via SSH and execute 'api status -s'
3. Send the output (.tgz file) + tool logs + export .tgz to royl@checkpoint.com

Thanks,
Roy
